### ISSUE TITLE
MSU的使用

### ISSUE THREAD

**Issue by xuhewei98** [iFe1er/SMU_pytorch#1]
这个东西真的有用吗？为啥我放到网络里也没有提升，是需要把整个网络的ReLu都换成SMU才有效果？

**Comment by iFe1er** [comment]
> 这个东西真的有用吗？为啥我放到网络里也没有提升，是需要把整个网络的ReLu都换成SMU才有效果？

肯定是都要换的，提升效果应该取决于你的具体任务，试试backbone的激活换成SMU再看看效果。

**Comment by koushik313** [comment]
@xuhewei98 , Yes, you need to replace all the ReLU activation functions (or any other activation used in the network) with the SMU function to see the effect.
